const RESEARCH_KEY='pininfo:research';
const FAVORITES_KEY='pininfo:favorites';
async function getState(){const d=await chrome.storage.local.get([RESEARCH_KEY,FAVORITES_KEY]);return{research:Array.isArray(d[RESEARCH_KEY])?d[RESEARCH_KEY]:[],favorites:Array.isArray(d[FAVORITES_KEY])?d[FAVORITES_KEY]:[]}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function num(v){if(v==null||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
function uniquePins(s){const map=new Map();[...s.research,...s.favorites].forEach(p=>{if(p?.url)map.set(p.url,p)});return[...map.values()]}
function csv(pins){const cols=['pin_id','pin_url','image_url','title','creator','creator_url','board','board_url','description','source_url','saves','impressions','pin_clicks','outbound_clicks','comments','published_at','observed_at','observed_from_url','keywords','research_score','trend_score','metrics_source','is_video'];const cell=v=>{const t=Array.isArray(v)?v.join(' | '):String(v??'');return /[",\n]/.test(t)?`"${t.replace(/"/g,'""')}"`:t};return['\ufeff'+cols.join(','),...pins.map(p=>cols.map(k=>cell(p[k])).join(','))].join('\n')}
function download(name,content,type){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function renderPins(pins){const list=document.querySelector('#pinList');const query=document.querySelector('#search').value.trim().toLowerCase();const sort=document.querySelector('#sort').value;let filtered=pins.filter(p=>!query||`${p.title||''} ${p.creator||''} ${(p.keywords||[]).join(' ')}`.toLowerCase().includes(query));filtered.sort((a,b)=>sort==='score'?(b.research_score||0)-(a.research_score||0):sort==='saves'?(b.saves||0)-(a.saves||0):sort==='comments'?(b.comments||0)-(a.comments||0):new Date(b.observed_at||0)-new Date(a.observed_at||0));document.querySelector('#resultCount').textContent=`${filtered.length} Pins`;if(!filtered.length){list.innerHTML='<div class="empty">No matching Pins.<br>Browse more on Pinterest or change the search.</div>';return}list.innerHTML=filtered.slice(0,100).map(p=>`<div class="pin-row"><img class="pin-thumb" src="${esc(p.image_url||'')}" alt=""><div class="pin-info"><div class="pin-title">${esc(p.title||'Untitled Pin')}</div><div class="pin-creator">${esc(p.creator||'Creator unavailable')}</div><div class="pin-tags">${esc((p.keywords||[]).slice(0,4).join(' · '))}</div></div><div class="pin-score"><b>${esc(p.research_score??0)}</b><small>SCORE</small></div></div>`).join('')}
async function refresh(){const s=await getState();const pins=uniquePins(s);document.querySelector('#researchCount').textContent=s.research.length;document.querySelector('#favoriteCount').textContent=s.favorites.length;const avg=pins.length?Math.round(pins.reduce((sum,p)=>sum+(Number(p.research_score)||0),0)/pins.length):0;document.querySelector('#avgScore').textContent=avg;renderPins(pins)}
document.querySelector('#search').addEventListener('input',refresh);document.querySelector('#sort').addEventListener('change',refresh);
document.querySelector('#exportCsv').addEventListener('click',async()=>{const s=await getState();download(`pininfo-research-${new Date().toISOString().slice(0,10)}.csv`,csv(uniquePins(s)),'text/csv;charset=utf-8')});
document.querySelector('#exportJson').addEventListener('click',async()=>{const s=await getState();download(`pininfo-research-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(s,null,2),'application/json')});
document.querySelector('#clearResearch').addEventListener('click',async()=>{await chrome.storage.local.set({[RESEARCH_KEY]:[]});refresh()});
document.querySelector('#clearFavorites').addEventListener('click',async()=>{await chrome.storage.local.set({[FAVORITES_KEY]:[]});refresh()});
document.querySelector('#diagnostic').addEventListener('click',async()=>{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id)return;chrome.tabs.sendMessage(tab.id,{type:'PININFO_RUN_DIAGNOSTIC'},()=>{});window.close()});
refresh();
